### ISSUE TITLE
Extra SHACL constraints compared to the XSD constraints

### ISSUE THREAD

**Issue by xuemduan** [Interoperable-data/ERA_vocabulary#12]
It seems that there are some additional constraints in the [SHACL shapes](https://data-interop.era.europa.eu/era-vocabulary/era-shapes) compared to the [RINF XSD Schema V1.5](https://www.era.europa.eu/system/files?file=2022-11/rinf_schema_en.xsd): some constraints which are available in the SHACL shapes are not present in XSD. 

For instance, the SHACL shape restricts the **wgs:lat latitude** should be between **34** and **73** but this constraint is not available in the XSD. Which one is correct?

In more detail:

- In SHACL there are **minInclusive** and **maxExclusive**

```
era-sh:locationShape sh:property era-sh:lat .
era-sh:lat
   a sh:PropertyShape;
   rdfs:comment "Latitude following the spatial reference system WGS84." ;
   sh:targetClass geosparql:Geometry ;
   sh:path wgs:lat ;
   sh:minCount 1 ;
   sh:maxCount 1 ;
   sh:minInclusive 34;
   sh:maxExclusive 73;
```

- But in XSD don’t have that, only have this:
```
<xs:attribute name="Latitude" type="xs:decimal" use="optional" />
```
In other cases, there is **sh:pattern** in property shape of **era:demonstrationINF** and **era:tafTAPCode**, which also does not appear in XSD.

**Comment by ednaru** [comment]
On the range of values for latitude, would need to check why it is restricted to these values. 
As for the rest of the validations that do not appear in the XSD schema, in SHACL shapes there is more completeness with respect to the reference RINF application guide; this is the case of the check for patterns in properties such as era:demonstrationINF and era:tafTAPCode where there are certain patterns according to the guide.
