### ISSUE TITLE
Commented constraints in SHACL shapes

### ISSUE THREAD

**Issue by xuemduan** [Interoperable-data/ERA_vocabulary#13]
Hi,

I noticed some constraints are commented like the **sh:minCount** in some [SHACL shapes](https://data-interop.era.europa.eu/era-vocabulary/era-shapes), could you explain what this means?       

Thanks in advance!

**Comment by ednaru** [comment]
What is commented is # sh:minCount 0, this is a case where in practice it is unrestricted, you may have 0 or more values so it seemed costly to have this check. That is the reason why it is commented.

**Comment by gatemezing** [comment]
Hi @xuemduan, could you confirm if the answer provided by @ednaru  answer your issue? if yes, maybe we could close the issue? TIA

**Comment by xuemduan** [comment]
Hi @gatemezing . Yes, it answers my question. It can be closed now. Thank you!!
