### ISSUE TITLE
Error in figure 1 of the documentation 

### ISSUE THREAD

**Issue by MathiasVDA** [Interoperable-data/ERA_vocabulary#8]
![image](https://github.com/Interoperable-data/ERA_vocabulary/assets/15101339/c4699f4f-f6a0-4ddc-87de-99f0b8b6cbb6)

Should be:
era:SystemSe**p**erationInfo

**Comment by ednaru** [comment]
Has been fixed in the dev version. Once we merge the laste version in Prod, you will see the fix.
