### ISSUE TITLE
Show inSkosConceptScheme property in the widoco documentation

### ISSUE THREAD

**Issue by MathiasVDA** [Interoperable-data/ERA_vocabulary#9]
In the TTL export of the vocabulary I see this:

```
###  http://data.europa.eu/949/navigability
:navigability rdf:type owl:ObjectProperty ;
              rdfs:domain :NetRelation ;
              rdfs:range <http://www.w3.org/2004/02/skos/core#Concept> ;
              :inSkosConceptScheme <http://data.europa.eu/949/concepts/navigabilities/Navigabilities> ;
              :rinfIndex "1.1.1.0.1.2" ,
                         "1.2.4.1" ;
              <http://purl.org/dc/terms/created> "2021-04-01"^^xsd:date ;
              <http://purl.org/dc/terms/modified> "2021-08-03"^^xsd:date ;
              <http://purl.org/dc/terms/source> <https://rsm-evolution.org/220927_RSM/EARoot/EA2/EA2/EA286.html> ;
              rdfs:comment "Indicates the navigation possibilities between two related topological objects. The allowed values for this property belong to the SKOS Concept Scheme http://data.europa.eu/949/concepts/navigabilities/Navigabilities."@en ;
              rdfs:isDefinedBy <http://data.europa.eu/949/> ;
              rdfs:label "Navigability"@en ;
              <http://www.w3.org/2003/06/sw-vocab-status/ns#term_status> "stable" ;
              <http://www.w3.org/2004/02/skos/core#altLabel> "Internal connection"@en .
```
The navigability has a property :inSkosConceptScheme that references the applicable conceptscheme. The widoco documentation however doesn't show this information:

![image](https://github.com/Interoperable-data/ERA_vocabulary/assets/15101339/33bbf285-4c34-4278-a9ea-bc7941b5349d)

The information is contained in the description of the class but I think this is not the right place. Now you have to manage both description and property and both can contain conflicting information. I propose to at least add the official information to the documentation (the property value) and maybe in time edit the descriptions to avoid duplicating information.

**Comment by ednaru** [comment]
The Widoco code would need to be tweaked in order to show additional metadata that we have been adding to the terms. In the meantime we have provided the URI of the concept in the definition that you can copy and paste (we have also added an  [issue](https://github.com/dgarijo/Widoco/issues/541)).

**Comment by gatemezing** [comment]
I was able to fix this by adding the correspond property like this one in the figure. We will use this version for the next release. 
<img width="1064" alt="profileNumberSwapBodies" src="https://github.com/Interoperable-data/ERA_vocabulary/assets/922883/77639c9d-88c3-4dbd-9f68-24f6c4f629b0">

**Comment by ednaru** [comment]
Widoco has been already improved for release 3.1.0. Will keep current Widoco for release 3.0.1.
